/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"
#import "TBase.h"


enum MDDeliveryStatus {
  DeliveryStatus_SUBMITTED = 1,
  DeliveryStatus_DELIVERING = 2,
  DeliveryStatus_COMPLETED = 10,
  DeliveryStatus_CANCELLED = 11
};

enum MDGender {
  Gender_FEMALE = 1,
  Gender_MALE = 2
};

enum MDErrorCode {
  ErrorCode_UNKNOWN = 1,
  ErrorCode_BAD_DATA_FORMAT = 2,
  ErrorCode_DATA_REQUIRED = 3,
  ErrorCode_INVALID_AUTH = 4
};

typedef int64_t MDTimestamp;

typedef NSString * MDAccessToken;

@interface MDCourier : NSObject <TBase, NSCoding> {
  int32_t __id;
  NSString * __name;
  NSString * __phone;
  int __gender;

  BOOL __id_isset;
  BOOL __name_isset;
  BOOL __phone_isset;
  BOOL __gender_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=id, setter=setId:) int32_t id;
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=phone, setter=setPhone:) NSString * phone;
@property (nonatomic, getter=gender, setter=setGender:) int gender;
#endif

- (id) init;
- (id) initWithId: (int32_t) id name: (NSString *) name phone: (NSString *) phone gender: (int) gender;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int32_t) id;
- (void) setId: (int32_t) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) phone;
- (void) setPhone: (NSString *) phone;
#endif
- (BOOL) phoneIsSet;

#if !__has_feature(objc_arc)
- (int) gender;
- (void) setGender: (int) gender;
#endif
- (BOOL) genderIsSet;

@end

@interface MDLatLng : NSObject <TBase, NSCoding> {
  double __lat;
  double __lng;

  BOOL __lat_isset;
  BOOL __lng_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=lat, setter=setLat:) double lat;
@property (nonatomic, getter=lng, setter=setLng:) double lng;
#endif

- (id) init;
- (id) initWithLat: (double) lat lng: (double) lng;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (double) lat;
- (void) setLat: (double) lat;
#endif
- (BOOL) latIsSet;

#if !__has_feature(objc_arc)
- (double) lng;
- (void) setLng: (double) lng;
#endif
- (BOOL) lngIsSet;

@end

@interface MDDelivery : NSObject <TBase, NSCoding> {
  NSString * __id;
  MDLatLng * __origin;
  MDLatLng * __destination;
  int __status;
  MDCourier * __courier;
  MDTimestamp __createdAt;

  BOOL __id_isset;
  BOOL __origin_isset;
  BOOL __destination_isset;
  BOOL __status_isset;
  BOOL __courier_isset;
  BOOL __createdAt_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=id, setter=setId:) NSString * id;
@property (nonatomic, retain, getter=origin, setter=setOrigin:) MDLatLng * origin;
@property (nonatomic, retain, getter=destination, setter=setDestination:) MDLatLng * destination;
@property (nonatomic, getter=status, setter=setStatus:) int status;
@property (nonatomic, retain, getter=courier, setter=setCourier:) MDCourier * courier;
@property (nonatomic, getter=createdAt, setter=setCreatedAt:) MDTimestamp createdAt;
#endif

- (id) init;
- (id) initWithId: (NSString *) id origin: (MDLatLng *) origin destination: (MDLatLng *) destination status: (int) status courier: (MDCourier *) courier createdAt: (MDTimestamp) createdAt;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (NSString *) id;
- (void) setId: (NSString *) id;
#endif
- (BOOL) idIsSet;

#if !__has_feature(objc_arc)
- (MDLatLng *) origin;
- (void) setOrigin: (MDLatLng *) origin;
#endif
- (BOOL) originIsSet;

#if !__has_feature(objc_arc)
- (MDLatLng *) destination;
- (void) setDestination: (MDLatLng *) destination;
#endif
- (BOOL) destinationIsSet;

#if !__has_feature(objc_arc)
- (int) status;
- (void) setStatus: (int) status;
#endif
- (BOOL) statusIsSet;

#if !__has_feature(objc_arc)
- (MDCourier *) courier;
- (void) setCourier: (MDCourier *) courier;
#endif
- (BOOL) courierIsSet;

#if !__has_feature(objc_arc)
- (MDTimestamp) createdAt;
- (void) setCreatedAt: (MDTimestamp) createdAt;
#endif
- (BOOL) createdAtIsSet;

@end

@interface MDServiceException : NSException <TBase, NSCoding> {
  int __code;
  NSString * __parameter;
  NSString * __message;

  BOOL __code_isset;
  BOOL __parameter_isset;
  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=code, setter=setCode:) int code;
@property (nonatomic, retain, getter=parameter, setter=setParameter:) NSString * parameter;
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) init;
- (id) initWithCode: (int) code parameter: (NSString *) parameter message: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (void) validate;

#if !__has_feature(objc_arc)
- (int) code;
- (void) setCode: (int) code;
#endif
- (BOOL) codeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) parameter;
- (void) setParameter: (NSString *) parameter;
#endif
- (BOOL) parameterIsSet;

#if !__has_feature(objc_arc)
- (NSString *) message;
- (void) setMessage: (NSString *) message;
#endif
- (BOOL) messageIsSet;

@end

@protocol MDDeliveryService <NSObject>
- (MDDelivery *) submitDelivery: (MDAccessToken) accessToken delivery: (MDDelivery *) delivery;  // throws MDServiceException *, TException
- (MDDelivery *) getDelivery: (MDAccessToken) accessToken deliveryId: (int32_t) deliveryId;  // throws MDServiceException *, TException
- (NSMutableArray *) listDeliveries: (MDAccessToken) accessToken offset: (int32_t) offset limit: (int32_t) limit;  // throws MDServiceException *, TException
- (MDDelivery *) assignCourier: (MDAccessToken) accessToken deliveryId: (int32_t) deliveryId courierId: (int32_t) courierId;  // throws MDServiceException *, TException
- (MDDelivery *) cancelDelivery: (MDAccessToken) accessToken deliveryId: (int32_t) deliveryId;  // throws MDServiceException *, TException
- (MDDelivery *) completeDelivery: (MDAccessToken) accessToken deliveryId: (int32_t) deliveryId;  // throws MDServiceException *, TException
@end

@interface MDDeliveryServiceClient : NSObject <MDDeliveryService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface MDDeliveryServiceProcessor : NSObject <TProcessor> {
  id <MDDeliveryService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithDeliveryService: (id <MDDeliveryService>) service;
- (id<MDDeliveryService>) service;
@end

@interface MDDeliveryConstants : NSObject {
}
@end
