/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.mesh.delivery;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 배송 상태
 */
public enum DeliveryStatus implements org.apache.thrift.TEnum {
  /**
   * 주문 접수됨
   */
  SUBMITTED(1),
  /**
   * 배송기사가 배정됨
   */
  DELIVERING(2),
  /**
   * 물품을 전달함
   */
  COMPLETED(10),
  /**
   * 배송 취소됨
   */
  CANCELLED(11);

  private final int value;

  private DeliveryStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static DeliveryStatus findByValue(int value) { 
    switch (value) {
      case 1:
        return SUBMITTED;
      case 2:
        return DELIVERING;
      case 10:
        return COMPLETED;
      case 11:
        return CANCELLED;
      default:
        return null;
    }
  }
}
