/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.mesh.delivery;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 오류 코드
 */
public enum ErrorCode implements org.apache.thrift.TEnum {
  /**
   * No information available about the error
   */
  UNKNOWN(1),
  /**
   * The format of the request data was incorrect
   */
  BAD_DATA_FORMAT(2),
  /**
   * A required parameter/field was absent
   */
  DATA_REQUIRED(3),
  /**
   * Access token is invalid
   */
  INVALID_AUTH(4);

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ErrorCode findByValue(int value) { 
    switch (value) {
      case 1:
        return UNKNOWN;
      case 2:
        return BAD_DATA_FORMAT;
      case 3:
        return DATA_REQUIRED;
      case 4:
        return INVALID_AUTH;
      default:
        return null;
    }
  }
}
